---
- name: Check and deploy website on NGINX server
  hosts: localhost
  become: yes
  tasks:
    - name: Check if NGINX is installed
      command: nginx -v
      ignore_errors: yes
      register: nginx_check

    - name: Install NGINX if not installed
      apt:
        name: nginx
        state: present
      when: nginx_check.rc != 0

    - name: Ensure NGINX is running
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Remove old website content
      file:
        path: /var/www/html/
        state: absent

    - name: Create website directory
      file:
        path: /var/www/html/
        state: directory

    - name: Copy website zip file to host
      copy:
        src: /home/shaikh-aftab/Desktop/jenkins/workspace/angular_pipeline/lots_of_money.zip
        dest: /tmp/project.zip

    - name: Unzip website content
      unarchive:
        src: /tmp/project.zip
        dest: /var/www/html/
        remote_src: yes

    - name: Remove default NGINX configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Restart NGINX

    - name: Create NGINX configuration for new website
      copy:
        content: |
          server {
              listen 8088;
              192.168.0.107;

              root /var/www/html;
              index index.html index.htm;

              location / {
                  try_files $uri $uri/ =404;
              }
          }
        dest: /etc/nginx/sites-available/my_website
      notify: Restart NGINX

    - name: Enable new NGINX site
      file:
        src: /etc/nginx/sites-available/my_website
        dest: /etc/nginx/sites-enabled/my_website
        state: link
      notify: Restart NGINX

  handlers:
    - name: Restart NGINX
      service:
        name: nginx
        state: restarted
