---
- name: Deploy Angular App with Docker
  hosts: docker_vm
  become: yes
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Remove existing Docker container if running
      docker_container:
        name: angular-app
        state: absent

    - name: Clean up old Docker images
      shell: docker image prune -f
      ignore_errors: yes

    - name: Upload the latest build to the server
      copy:
        src: /local/path/to/latest-build/
        dest: /tmp/latest-build/
        mode: "0755"
    
    - name: Copy Dockerfile and nginx.conf to the deployment directory
      copy:
        src: "docker/"
        dest: "/tmp/latest-build/docker/"

    - name: Build Docker image for Angular App using Dockerfile
      docker_image:
        path: "/tmp/latest-build"
        dockerfile: "/tmp/latest-build/docker/Dockerfile"
        name: angular-app:latest

    - name: Run Docker container for Angular App
      docker_container:
        name: angular-app
        image: angular-app:latest
        state: started
        ports:
          - "4545:4545"
        restart_policy: always